import { useEffect, useMemo, useState } from 'react';
import { Link, useBlocker, useNavigate } from 'react-router-dom';
import { Search, Plus, ArrowLeft, Check, Pencil, Trash2 } from 'lucide-react';
import { Layout } from '../components/Layout';
import { Button } from '../components/ui/Button';
import { apiClient, parseApiError } from '../services/api';
import type { BenchmarkAccount, BenchmarkSample, BenchmarkView, BenchmarkSearchResult } from '../../../src/lib/wechat-benchmarks';
import type { WechatSearchArticle } from '../../../src/lib/wechat-search';
import { benchmarkDirty } from '../utils/navigationGuards';

const inputClass='mt-2 w-full rounded-lg border border-line-ui bg-canvas px-3 py-2 text-sm text-ink focus:border-accent focus:ring-1 focus:ring-accent';
type AccountEdit=Omit<BenchmarkAccount,'samples'> & {samples:Array<Omit<BenchmarkSample,'reads'|'lowerBound'> & {readsText:string}>};
type SettingsEdit={name:string;audience:string;keywordText:string;minReadsText:string};
const blankSample=()=>({title:'',url:'',dateText:'',readsText:'',metricSource:'',measuredAt:''});
const blankAccount=():AccountEdit=>({id:'',name:'',identity:'',identityConfirmed:false,relevant:false,selected:false,notes:'',samples:[]});
function describeAccount(a:AccountEdit){return `${a.name}\n账号标识：${a.identity}\n身份确认：${a.identityConfirmed?'已确认':'待核验'}；相关性：${a.relevant?'已确认':'待确认'}；选择：${a.selected?'已选':'未选'}\n写作观察：${a.notes}\n${a.samples.map(s=>`${s.title}\n${s.url}\n阅读：${s.readsText||'未知'}；来源：${s.metricSource||'未知'}；观察时间：${s.measuredAt||'未知'}`).join('\n\n')}`;}
function editAccount(a:BenchmarkAccount):AccountEdit{return {...a,samples:a.samples.map(({reads,lowerBound,...s})=>({...s,readsText:reads===null?'':`${reads}${lowerBound?'+':''}`}))};}
function saveAccount(a:AccountEdit){return {...a,samples:a.samples.map(({readsText,...s})=>{
  const value=readsText.trim();if(!value)return {...s,reads:null,lowerBound:false};
  if(value==='10万+')return {...s,reads:100000,lowerBound:true};
  if(!/^\d+\+?$/.test(value))throw new Error('阅读量请填整数、100000+ 或 10万+；未知请留空');
  return {...s,reads:Number(value.replace('+','')),lowerBound:value.endsWith('+')};
})};}
function Field({label,value,onChange,multiline=false,maxLength=2000}:{label:string;value:string;onChange:(s:string)=>void;multiline?:boolean;maxLength?:number}){
  return <label className="block text-xs font-medium text-ink-muted">{label}{multiline?<textarea aria-label={label} value={value} onChange={e=>onChange(e.target.value)} rows={3} maxLength={maxLength} className={inputClass}/>:<input aria-label={label} value={value} onChange={e=>onChange(e.target.value)} maxLength={maxLength} className={inputClass}/>}</label>;
}

export function WechatBenchmarksPage(){
  const navigate=useNavigate();const [groups,setGroups]=useState<BenchmarkView[]>([]);const [activeId,setActiveId]=useState('');
  const group=groups.find(g=>g.id===activeId);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const initialNew=useMemo(()=>{try{const raw=sessionStorage.getItem('douyin-ai-video.benchmark-new');if(!raw)return null;const p=JSON.parse(raw);if(typeof p.name!=='string'||typeof p.audience!=='string'||typeof p.keywords!=='string')return null;return p as {name:string;audience:string;keywords:string};}catch{return null;}},[]);
  const [newName,setNewName]=useState(initialNew?.name??'');const [newAudience,setNewAudience]=useState(initialNew?.audience??'');const [newKeywords,setNewKeywords]=useState(initialNew?.keywords??'');const [creating,setCreating]=useState(!!initialNew);
  const [settings,setSettings]=useState<SettingsEdit|null>(null);const [editor,setEditor]=useState<AccountEdit|null>(null);const [editVersion,setEditVersion]=useState(0);
  const [keyword,setKeyword]=useState('');const [result,setResult]=useState<BenchmarkSearchResult>();const [target,setTarget]=useState('');const [topic,setTopic]=useState('');
  const [needsReload,setNeedsReload]=useState(false);const [conflict,setConflict]=useState<BenchmarkView|null>(null);
  const dirty=benchmarkDirty({settings:!!settings,editor:!!editor,creating,newName,newAudience,newKeywords});
  const blocker=useBlocker(({currentLocation,nextLocation})=>dirty&&currentLocation.pathname!==nextLocation.pathname);
  useEffect(()=>{let live=true;void apiClient.getWechatBenchmarks().then(items=>{if(!live)return;let preferred='';try{preferred=sessionStorage.getItem('douyin-ai-video.benchmark-active')??'';}catch{}const chosen=items.find(g=>g.id===preferred)??items[0];setGroups(items);setActiveId(chosen?.id??'');setKeyword(chosen?.keywords[0]??'');}).catch(e=>{if(live)setError(parseApiError(e).message);});return()=>{live=false;};},[]);
  useEffect(()=>{if(activeId)try{sessionStorage.setItem('douyin-ai-video.benchmark-active',activeId);}catch{}},[activeId]);
  useEffect(()=>{try{const key='douyin-ai-video.benchmark-new';if(newName||newAudience||newKeywords)sessionStorage.setItem(key,JSON.stringify({name:newName,audience:newAudience,keywords:newKeywords}));else sessionStorage.removeItem(key);}catch{setError('新建组输入无法临时备份，请及时保存');}},[newName,newAudience,newKeywords]);
  useEffect(()=>{if(!activeId)return;const key=`douyin-ai-video.benchmark-edit.${activeId}`;try{const raw=sessionStorage.getItem(key);if(raw){const saved=JSON.parse(raw);setSettings(saved.settings??null);setEditor(saved.editor??null);setEditVersion(saved.version);setNotice('已恢复未保存编辑；保存时仍会核对原版本。');}}catch{setError('本地编辑记录不可读取，请重新编辑');}},[activeId]);
  useEffect(()=>{if(!activeId)return;try{const key=`douyin-ai-video.benchmark-edit.${activeId}`;if(settings||editor)sessionStorage.setItem(key,JSON.stringify({settings,editor,version:editVersion}));else sessionStorage.removeItem(key);}catch{setError('未保存编辑无法临时备份，请及时保存');}},[activeId,settings,editor,editVersion]);
  useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[dirty]);
  const put=(g:BenchmarkView)=>setGroups(items=>[g,...items.filter(i=>i.id!==g.id)]);
  const changeGroup=(id:string)=>{if(dirty&&!window.confirm('切换对标组会放弃当前未保存编辑，继续？'))return;if(activeId)sessionStorage.removeItem(`douyin-ai-video.benchmark-edit.${activeId}`);setSettings(null);setEditor(null);setNewName('');setNewAudience('');setNewKeywords('');setCreating(false);setNeedsReload(false);setConflict(null);setActiveId(id);setResult(undefined);setTarget('');setKeyword(groups.find(g=>g.id===id)?.keywords[0]??'');setError('');};
  const patch=async(data:Record<string,unknown>,version=group?.version,finish=false)=>{
    if(!group||version===undefined)return;setBusy(true);setError('');setNotice('');
    try{const updated=await apiClient.saveWechatBenchmark(group.id,{...data,version});put(updated);if(finish){setSettings(null);setEditor(null);}setNeedsReload(false);setConflict(null);setNotice('对标记录已保存');}
    catch(e){const parsed=parseApiError(e);setError(parsed.message);if(parsed.status===409)setNeedsReload(true);}finally{setBusy(false);}
  };
  const create=async()=>{setBusy(true);setError('');try{const g=await apiClient.createWechatBenchmark({name:newName,audience:newAudience,keywords:newKeywords.split('\n').map(s=>s.trim()).filter(Boolean),minReads:1000});put(g);setSettings(null);setEditor(null);setActiveId(g.id);setKeyword(g.keywords[0]??'');setNewName('');setNewAudience('');setNewKeywords('');setCreating(false);setResult(undefined);setTarget('');}catch(e){setError(parseApiError(e).message);}finally{setBusy(false);}};
  const search=async()=>{setBusy(true);setError('');try{setResult(await apiClient.searchWechatBenchmarks(keyword||group?.keywords[0]||''));}catch(e){setError(parseApiError(e).message);}finally{setBusy(false);}};
  const addResult=async(item:WechatSearchArticle)=>{
    if(!group)return;const sample:BenchmarkSample={title:item.title,url:item.url,dateText:item.dateText,reads:null,lowerBound:false,metricSource:'',measuredAt:''};
    const existing=group.accounts.find(a=>a.id===target);
    if(existing){if(existing.samples.some(s=>s.url===item.url)){setError('此账号已保存这篇文章');return;}await patch({account:{...existing,samples:[...existing.samples,sample]}});}
    else await patch({addAccount:{name:item.accountName,identity:'',identityConfirmed:false,relevant:false,selected:false,notes:'',samples:[sample]}});
  };
  const beginEdit=(a?:BenchmarkAccount)=>{if(dirty&&!window.confirm('放弃当前未保存编辑，改为编辑这个账号？'))return;setSettings(null);setEditor(a?editAccount(a):blankAccount());setEditVersion(group!.version);setError('');};
  const saveEditor=()=>{if(!editor)return;try{void patch({[editor.id?'account':'addAccount']:saveAccount(editor)},editVersion,true);}catch(e){setError((e as Error).message);}};
  const discard=()=>{setSettings(null);setEditor(null);setNeedsReload(false);setConflict(null);setError('');};
  const loadLatest=async()=>{if(!group)return;setBusy(true);try{const latest=(await apiClient.getWechatBenchmarks()).find(g=>g.id===group.id);if(!latest)throw new Error('对标组已被删除，当前输入仍保留，请先复制需要保留的内容');setConflict(latest);setError('请对照最新保存内容，再决定是否继续使用当前编辑。');}catch(e){setError(parseApiError(e).message);}finally{setBusy(false);}};
  const useMyEdit=()=>{if(!conflict)return;put(conflict);setEditVersion(conflict.version);if(editor?.id&&!conflict.accounts.some(a=>a.id===editor.id))setEditor({...editor,id:''});setConflict(null);setNeedsReload(false);setError('');setNotice('当前输入已保留。再次保存会覆盖对照中显示的已保存字段，请先检查。');};
  const startArticle=async()=>{if(!group)return;setBusy(true);setError('');try{const a=await apiClient.createArticle({keyword:topic,benchmarkId:group.id});navigate(`/articles/${a.id}`);}catch(e){setError(parseApiError(e).message);}finally{setBusy(false);}};
  const editSample=(i:number,p:Partial<AccountEdit['samples'][number]>)=>setEditor(a=>a?{...a,samples:a.samples.map((s,j)=>i===j?{...s,...p}:s)}:a);

  return <Layout><div className="mx-auto max-w-6xl space-y-7 p-5 sm:p-8">
    <Link to="/articles" className="inline-flex items-center gap-2 text-xs text-ink-muted hover:text-accent"><ArrowLeft size={14}/>文章创作</Link>
    <header className="space-y-3"><p className="text-xs tracking-widest text-accent">公众号起号 · 对标研究</p><h1 className="font-display text-3xl font-semibold text-ink">找到同行，核对表现，再确定写法</h1><p className="max-w-3xl text-sm leading-7 text-ink-muted">自己选择领域与读者。公开搜索提供文章和账号线索；阅读量由你核对来源后录入，达到门槛的账号才计入有效对标。</p></header>
    {error&&<p role="alert" className="rounded-lg border border-danger-line bg-danger-soft p-3 text-sm text-danger">{error}</p>}
    {notice&&<p role="status" className="text-sm text-accent">{notice}</p>}
    {needsReload&&!conflict&&<Button variant="outline" disabled={busy} onClick={()=>void loadLatest()}>载入最新版本，保留编辑</Button>}
    {conflict&&<section className="space-y-4 rounded-xl border border-warning-line bg-warning-soft p-5"><h2 className="text-base font-semibold text-ink">核对版本变化</h2><p className="text-xs leading-6 text-ink-muted">选择继续使用当前编辑后，下一次保存会覆盖下方对应的已保存字段。请先核对样本和观察内容。</p><div className="grid gap-4 lg:grid-cols-2"><section><h3 className="text-xs font-medium text-ink">最新保存内容</h3><p className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap break-words text-xs leading-6 text-ink-muted">{editor?(()=>{const latest=conflict.accounts.find(a=>a.id===editor.id);return latest?describeAccount(editAccount(latest)):'该账号尚未保存或已被移除；可以另存为新候选。';})():`${conflict.name}\n读者：${conflict.audience}\n关键词：${conflict.keywords.join('、')}\n阅读门槛：${conflict.minReads}`}</p></section><section><h3 className="text-xs font-medium text-ink">当前未保存编辑</h3><p className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap break-words text-xs leading-6 text-ink-muted">{editor?describeAccount(editor):settings?`${settings.name}\n读者：${settings.audience}\n关键词：${settings.keywordText}\n阅读门槛：${settings.minReadsText}`:'没有表单编辑'}</p></section></div><Button disabled={busy} onClick={useMyEdit}>继续使用我的编辑</Button><Button variant="ghost" disabled={busy} onClick={()=>{put(conflict);discard();}}>采用已保存内容，放弃本次编辑</Button></section>}
    {blocker.state==='blocked'&&<section role="alert" className="sticky top-14 z-40 flex flex-wrap items-center gap-3 rounded-lg border border-warning-line bg-warning-soft p-4 text-sm text-warning shadow-md"><span>对标编辑尚未保存，已拦下本次跳转。</span><Button size="sm" onClick={()=>blocker.reset()}>继续编辑</Button><Button size="sm" variant="outline" onClick={()=>blocker.proceed()}>离开并保留临时编辑</Button></section>}
    <fieldset disabled={busy} className="space-y-7 disabled:opacity-70">
      <div className="flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1 text-xs text-ink-muted">对标组<select aria-label="对标组" value={activeId} onChange={e=>changeGroup(e.target.value)} className={inputClass}>{!groups.length&&<option value="">尚未建立对标组</option>}{groups.map(g=><option key={g.id} value={g.id}>{g.name} · {g.assessment.qualifiedCount} 个有效对标</option>)}</select></label><Button variant="outline" disabled={!!editor||!!settings} onClick={()=>setCreating(v=>!v)}><Plus size={15}/>新建对标组</Button><Button variant="ghost" onClick={()=>{if(dirty&&!window.confirm('重载会放弃当前未保存编辑，继续？'))return;discard();setNewName('');setNewAudience('');setNewKeywords('');setCreating(false);void apiClient.getWechatBenchmarks().then(setGroups).catch(e=>setError(parseApiError(e).message));}}>重载已保存记录</Button></div>
      {(creating||!groups.length)&&<form onSubmit={e=>{e.preventDefault();void create();}} className="space-y-4 rounded-xl border border-line bg-panel p-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="领域 / 对标组名称" value={newName} maxLength={100} onChange={setNewName}/><Field label="目标读者（可选）" value={newAudience} onChange={setNewAudience}/></div><Field label="搜索关键词（每行一个，最多 10 个）" value={newKeywords} maxLength={1100} onChange={setNewKeywords} multiline/><Button type="submit" disabled={!newName.trim()||!newKeywords.trim()}>建立对标组</Button></form>}
      {group&&<>
        <section className="rounded-xl border border-line bg-panel p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-display text-xl font-semibold text-ink">{group.name}</h2><p className="mt-2 text-sm text-ink-muted">{group.audience||'目标读者尚未填写'} · 关键词：{group.keywords.join('、')}</p><p className="mt-2 text-xs leading-6 text-ink-muted">样本阅读中位数门槛 {group.minReads.toLocaleString()}，可按赛道调整。判断基于用户录入的数据，保留来源、时间和样本量。</p></div><Button variant="ghost" disabled={dirty} onClick={()=>{setEditor(null);setEditVersion(group.version);setSettings({name:group.name,audience:group.audience,keywordText:group.keywords.join('\n'),minReadsText:String(group.minReads)});}}><Pencil size={14}/>编辑领域与门槛</Button></div>
          <div className="mt-5 border-t border-line pt-4"><p className="text-sm text-ink"><strong className="text-accent">{group.assessment.qualifiedCount} / 10</strong> 个有效对标 · 已选 {group.assessment.selectedCount} 个 · 候选 {group.accounts.length} 个</p><p className="mt-2 text-xs text-ink-muted">{group.assessment.qualifiedCount>=10?'可以带着对标参考开始创作。':'继续补充并核验账号；身份、相关性或阅读依据不足的候选暂不计入。'}</p></div>
        </section>
        {settings&&<form onSubmit={e=>{e.preventDefault();void patch({name:settings.name,audience:settings.audience,keywords:settings.keywordText.split('\n').map(s=>s.trim()).filter(Boolean),minReads:Number(settings.minReadsText)},editVersion,true);}} className="space-y-4 rounded-xl border border-accent-line bg-panel p-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="领域名称" value={settings.name} maxLength={100} onChange={name=>setSettings({...settings,name})}/><Field label="目标读者" value={settings.audience} onChange={audience=>setSettings({...settings,audience})}/><Field label="阅读中位数门槛" value={settings.minReadsText} maxLength={10} onChange={minReadsText=>setSettings({...settings,minReadsText})}/></div><Field label="关键词（每行一个）" value={settings.keywordText} maxLength={1100} onChange={keywordText=>setSettings({...settings,keywordText})} multiline/><div className="flex gap-3"><Button type="submit">保存领域与门槛</Button><Button variant="ghost" onClick={discard}>取消编辑</Button></div></form>}
        <section className="space-y-4 rounded-xl border border-line bg-panel p-5"><h2 className="text-lg font-semibold text-ink">发现相关文章与账号</h2><form onSubmit={e=>{e.preventDefault();void search();}} className="flex flex-col items-end gap-3 sm:flex-row"><label className="w-full flex-1 text-xs text-ink-muted">检索关键词<input aria-label="检索关键词" value={keyword} onChange={e=>setKeyword(e.target.value)} maxLength={100} className={inputClass}/></label><Button type="submit" disabled={dirty||!keyword.trim()}><Search size={15}/>搜索文章线索</Button></form><p className="text-xs leading-6 text-ink-muted">来源：搜狗微信公开搜索。结果不含阅读量，排序不代表账号流量；每次公开请求至少间隔 60 秒。</p><a className="text-xs text-accent hover:underline" href={`https://weixin.sogou.com/weixin?type=2&query=${encodeURIComponent(keyword)}`} target="_blank" rel="noreferrer">打开搜狗手动搜索 →</a>
          {result&&<><p className="text-xs text-ink-muted">“{result.keyword}” · {result.articles.length} 篇文章 · {result.cached?'缓存结果':'本次结果'} · {new Date(result.fetchedAt).toLocaleString('zh-CN')}</p><label className="block text-xs text-ink-muted">保存到<select aria-label="搜索结果保存到" value={target} onChange={e=>setTarget(e.target.value)} className={inputClass}><option value="">建立新的待核验候选</option>{group.accounts.map(a=><option key={a.id} value={a.id}>{a.name}（添加样本，由你确认归属）</option>)}</select></label><div className="divide-y divide-line">{result.articles.map(item=><article key={item.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-start"><div className="min-w-0 flex-1"><a href={item.url} target="_blank" rel="noreferrer" className="text-sm font-medium leading-6 text-ink hover:text-accent">{item.title}</a><p className="mt-2 text-xs text-ink-muted">{item.accountName} · {item.dateText||'发布时间未知'} · 阅读量未知</p><p className="mt-2 text-xs leading-6 text-ink-subtle">{item.summary}</p></div><Button size="sm" variant="outline" disabled={dirty} onClick={()=>void addResult(item)}>保存候选 / 样本</Button></article>)}</div>{!result.articles.length&&<p className="text-sm text-ink-muted">没有找到结果。换一个关键词，或手动补充账号与文章。</p>}</>}
        </section>
        <section className="space-y-4"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-semibold text-ink">候选与对标比较</h2><Button variant="outline" disabled={dirty} onClick={()=>beginEdit()}><Plus size={15}/>手动补充账号</Button></div><p className="text-xs leading-6 text-ink-muted">“10 万+”是下界。样本含下界时中位数也标为下界；单篇样本仅代表该篇表现。核验身份时请检查账号主页或已知微信号，昵称相同不代表同一账号。</p>
          <div className="divide-y divide-line rounded-xl border border-line bg-panel">{[...group.accounts].sort((a,b)=>(group.assessment.accounts.find(s=>s.id===b.id)?.medianReads??-1)-(group.assessment.accounts.find(s=>s.id===a.id)?.medianReads??-1)).map(a=>{const stats=group.assessment.accounts.find(s=>s.id===a.id)!;return <article key={a.id} className="grid gap-4 p-5 lg:grid-cols-[1.1fr_.7fr_1.5fr_auto]"><div><label className="flex items-start gap-2 text-sm font-medium text-ink"><input aria-label={`选中${a.name}`} type="checkbox" checked={a.selected} disabled={dirty} onChange={e=>void patch({account:{...a,selected:e.target.checked}})} className="mt-1"/>{a.name}</label><p className="mt-2 break-all text-xs text-ink-subtle">{a.identity||'身份待核验'}</p></div><div><p className="text-sm font-medium text-ink">{stats.medianReads===null?'阅读未知':`${stats.lowerBound?'≥ ':''}${stats.medianReads.toLocaleString()}`}</p><p className="mt-1 text-xs text-ink-muted">{stats.sampleCount} 篇有阅读依据 · 共 {a.samples.length} 篇</p></div><div>{stats.qualified?<p className="flex items-center gap-1 text-xs text-success"><Check size={13}/>计入有效对标</p>:<p className="text-xs text-warning">{stats.reasons.join(' · ')||'符合门槛，尚未选中'}</p>}<p className="mt-2 text-xs leading-6 text-ink-muted">{a.notes||'尚未记录写作观察'}</p><details className="mt-2 text-xs text-ink-muted"><summary className="cursor-pointer">查看标题与数据来源</summary><ul className="mt-2 space-y-3">{a.samples.map((s,i)=><li key={i}><a href={s.url} target="_blank" rel="noreferrer" className="text-accent hover:underline">{s.title}</a><p className="mt-1">{s.reads===null?'阅读量未知':`${s.lowerBound?'≥ ':''}${s.reads.toLocaleString()} · 用户录入：${s.metricSource} · ${new Date(s.measuredAt).toLocaleString('zh-CN')}`}</p></li>)}</ul></details></div><div className="flex items-start gap-1"><Button size="sm" variant="ghost" disabled={dirty} onClick={()=>beginEdit(a)}>编辑与核验</Button><button aria-label={`移除${a.name}`} disabled={dirty} onClick={()=>{if(window.confirm(`移除「${a.name}」及其样本？`))void patch({removeAccountId:a.id});}} className="rounded p-2 text-ink-muted hover:text-danger focus-visible:ring-2 focus-visible:ring-accent"><Trash2 size={14}/></button></div></article>;})}{!group.accounts.length&&<p className="p-8 text-center text-sm text-ink-muted">先搜索文章线索，或手动添加你已找到的公众号。</p>}</div>
        </section>
        {editor&&<form onSubmit={e=>{e.preventDefault();saveEditor();}} className="space-y-5 rounded-xl border border-accent-line bg-panel p-5"><h2 className="text-lg font-semibold text-ink">{editor.id?'编辑账号与阅读依据':'补充候选账号'}</h2><div className="grid gap-4 sm:grid-cols-2"><Field label="公众号名称" value={editor.name} maxLength={100} onChange={name=>setEditor({...editor,name})}/><Field label="核验后的微信号 / 账号唯一标识" value={editor.identity} maxLength={200} onChange={identity=>setEditor({...editor,identity,identityConfirmed:false})}/></div><p className="text-xs text-ink-muted">文章链接包含账号标识时自动用于去重；搜索昵称仍需人工核对。</p><div className="flex flex-wrap gap-4 text-sm text-ink">{([{key:'identityConfirmed',label:'已核对账号身份'},{key:'relevant',label:'已确认同赛道 / 同读者'},{key:'selected',label:'选为对标'}] as const).map(c=><label key={c.key}><input type="checkbox" checked={editor[c.key]} onChange={e=>setEditor({...editor,[c.key]:e.target.checked})}/> {c.label}</label>)}</div><Field label="写作观察（选题、开头、结构、语气、排版及适用条件）" value={editor.notes} onChange={notes=>setEditor({...editor,notes})} multiline/>
          <div className="flex items-center justify-between gap-3"><h3 className="text-sm font-semibold text-ink">文章样本与阅读依据</h3><Button size="sm" variant="outline" disabled={editor.samples.length>=20} onClick={()=>setEditor({...editor,samples:[...editor.samples,blankSample()]})}>添加文章样本</Button></div>
          {editor.samples.map((s,i)=><section key={i} className="space-y-4 rounded-lg border border-line bg-canvas p-4"><div className="flex items-center justify-between"><h4 className="text-xs font-medium text-ink">样本 {i+1}</h4><Button size="sm" variant="ghost" onClick={()=>setEditor({...editor,samples:editor.samples.filter((_,j)=>i!==j)})}>移除样本</Button></div><div className="grid gap-4 sm:grid-cols-2"><Field label={`样本${i+1}文章标题`} value={s.title} maxLength={500} onChange={title=>editSample(i,{title})}/><Field label={`样本${i+1}文章链接`} value={s.url} maxLength={4096} onChange={url=>{editSample(i,{url});setEditor(a=>a?{...a,identityConfirmed:false}:a);}}/><Field label={`样本${i+1}阅读量（未知留空，支持 10万+）`} value={s.readsText} maxLength={20} onChange={readsText=>editSample(i,{readsText})}/><Field label={`样本${i+1}阅读数据来源`} value={s.metricSource} maxLength={500} onChange={metricSource=>editSample(i,{metricSource})}/><Field label={`样本${i+1}发布时间（可选）`} value={s.dateText} maxLength={100} onChange={dateText=>editSample(i,{dateText})}/><div><Field label={`样本${i+1}观察时间（带时区的日期时间）`} value={s.measuredAt} maxLength={100} onChange={measuredAt=>editSample(i,{measuredAt})}/><Button size="sm" variant="ghost" onClick={()=>editSample(i,{measuredAt:new Date().toISOString()})}>记录当前观察时间</Button></div></div></section>)}
          <p className="text-xs leading-6 text-ink-muted">数字需有数据来源和观察时间。公开搜索摘要可用于发现选题，不能作为完整原文或流量证据。</p><div className="flex gap-3"><Button type="submit">保存账号与依据</Button><Button variant="ghost" onClick={discard}>取消编辑</Button></div>
        </form>}
        <section className="space-y-4 rounded-xl border border-line bg-panel p-5"><h2 className="text-lg font-semibold text-ink">把对标观察带入新文章</h2><p className="text-xs leading-6 text-ink-muted">复用领域、读者、标题参考和写作观察。文章事实仍需在工作台另行补充可追溯资料。</p><Field label="这篇文章的选题 / 关键词" value={topic} maxLength={500} onChange={setTopic}/><Button disabled={dirty||!topic.trim()||group.assessment.qualifiedCount<10} onClick={()=>void startArticle()}>使用有效对标开始创作</Button></section>
        <button type="button" disabled={dirty} onClick={()=>{if(window.confirm(`删除对标组「${group.name}」及全部样本？已经创建的文章会保留。`)){setBusy(true);void apiClient.removeWechatBenchmark(group.id,group.version).then(()=>{setGroups(groups.filter(g=>g.id!==group.id));setActiveId(groups.find(g=>g.id!==group.id)?.id??'');setResult(undefined);setTarget('');}).catch(e=>setError(parseApiError(e).message)).finally(()=>setBusy(false));}}} className="text-xs text-ink-muted hover:text-danger">删除这个对标组</button>
      </>}
    </fieldset>
  </div></Layout>;
}
